---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos7.5-vagrant
    box: centos/7
    # centos7.5 image
    # https://app.vagrantup.com/centos/boxes/7
    # https://blog.centos.org/2018/05/updated-centos-vagrant-images-available-v1804-02/
    box_version: "1804.02"
    cpus: 1
    memory: 2048
provisioner:
  name: ansible
  options:
    become: True
  lint:
    name: ansible-lint
    options:
      R: True
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../tests
  options:
    verbose: True
  lint:
    name: flake8
